name: Update Daily Word

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:

  schedule:
    - cron: '0 4,0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: Build daily word
      - run: npm run build
        env:
          PAGE_URI: ${{ secrets.PAGE_URI }}
      - name: Ganerate DAILY.JSON with lastest info
      - run: |
          git config user.name gabriedev
          git config user.email gabriedev@gmail.com
          git add daily.json
          git diff --quiet && git diff --staged --quiet || git commit -m "[bot] Update daily word with latest info"
          git push origin main
